-- begin DEALERAPP_CAR_CONFIGURATION
alter table DEALERAPP_CAR_CONFIGURATION add constraint FK_DEALERAPP_CAR_CONFIGURATION_ON_CAR_BRAND foreign key (CAR_BRAND_ID) references DEALERAPP_CAR_BRAND(ID)^
create unique index UNIQUE_BRAND_NAME_IDX on DEALERAPP_CAR_CONFIGURATION (CAR_BRAND_ID, NAME) ^
create index IDX_DEALERAPP_CAR_CONFIGURATION_ON_CAR_BRAND on DEALERAPP_CAR_CONFIGURATION (CAR_BRAND_ID)^
-- end DEALERAPP_CAR_CONFIGURATION
-- begin DEALERAPP_REQUEST
alter table DEALERAPP_REQUEST add constraint FK_DEALERAPP_REQUEST_ON_CAR foreign key (CAR_ID) references DEALERAPP_CAR(ID)^
alter table DEALERAPP_REQUEST add constraint FK_DEALERAPP_REQUEST_ON_CONTRACTOR foreign key (CONTRACTOR_ID) references DEALERAPP_CONTRACTOR(ID)^
alter table DEALERAPP_REQUEST add constraint FK_DEALERAPP_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_DEALERAPP_REQUEST_ON_CAR on DEALERAPP_REQUEST (CAR_ID)^
create index IDX_DEALERAPP_REQUEST_ON_CONTRACTOR on DEALERAPP_REQUEST (CONTRACTOR_ID)^
create index IDX_DEALERAPP_REQUEST_ON_MANAGER on DEALERAPP_REQUEST (MANAGER_ID)^
-- end DEALERAPP_REQUEST
-- begin DEALERAPP_CAR_BRAND
alter table DEALERAPP_CAR_BRAND add constraint FK_DEALERAPP_CAR_BRAND_ON_CAR_MAKER foreign key (CAR_MAKER_ID) references DEALERAPP_CAR_MAKER(ID)^
create unique index UNIQUE_NAME_CAR_MAKER_IDX on DEALERAPP_CAR_BRAND (CAR_MAKER_ID, NAME) ^
create index IDX_DEALERAPP_CAR_BRAND_ON_CAR_MAKER on DEALERAPP_CAR_BRAND (CAR_MAKER_ID)^
-- end DEALERAPP_CAR_BRAND
-- begin DEALERAPP_CAR
alter table DEALERAPP_CAR add constraint FK_DEALERAPP_CAR_ON_CAR_MAKER foreign key (CAR_MAKER_ID) references DEALERAPP_CAR_MAKER(ID)^
alter table DEALERAPP_CAR add constraint FK_DEALERAPP_CAR_ON_CAR_BRAND foreign key (CAR_BRAND_ID) references DEALERAPP_CAR_BRAND(ID)^
alter table DEALERAPP_CAR add constraint FK_DEALERAPP_CAR_ON_CAR_CONFIGURATION foreign key (CAR_CONFIGURATION_ID) references DEALERAPP_CAR_CONFIGURATION(ID)^
create index IDX_DEALERAPP_CAR_ON_CAR_MAKER on DEALERAPP_CAR (CAR_MAKER_ID)^
create index IDX_DEALERAPP_CAR_ON_CAR_BRAND on DEALERAPP_CAR (CAR_BRAND_ID)^
create index IDX_DEALERAPP_CAR_ON_CAR_CONFIGURATION on DEALERAPP_CAR (CAR_CONFIGURATION_ID)^
-- end DEALERAPP_CAR
-- begin DEALERAPP_COMPANY
alter table DEALERAPP_COMPANY add constraint FK_DEALERAPP_COMPANY_ON_ID foreign key (ID) references DEALERAPP_CONTRACTOR(ID) on delete CASCADE^
-- end DEALERAPP_COMPANY
-- begin DEALERAPP_PERSON
alter table DEALERAPP_PERSON add constraint FK_DEALERAPP_PERSON_ON_ID foreign key (ID) references DEALERAPP_CONTRACTOR(ID) on delete CASCADE^
-- end DEALERAPP_PERSON
-- begin DEALERAPP_CAR_MAKER
alter table DEALERAPP_CAR_MAKER add constraint FK_DEALERAPP_CAR_MAKER_ON_COUNTRY foreign key (COUNTRY_ID) references DEALERAPP_COUNTRY(ID)^
create unique index IDX_DEALERAPP_CAR_MAKER_UNIQ_NAME on DEALERAPP_CAR_MAKER (NAME) ^
create unique index IDX_DEALERAPP_CAR_MAKER_UNIQ_CODE on DEALERAPP_CAR_MAKER (CODE) ^
create index IDX_DEALERAPP_CAR_MAKER_ON_COUNTRY on DEALERAPP_CAR_MAKER (COUNTRY_ID)^
-- end DEALERAPP_CAR_MAKER
-- begin DEALERAPP_COLOR
create unique index IDX_DEALERAPP_COLOR_UNIQ_CODE on DEALERAPP_COLOR (CODE) ^
create unique index IDX_DEALERAPP_COLOR_UNIQ_NAME on DEALERAPP_COLOR (NAME) ^
-- end DEALERAPP_COLOR
-- begin DEALERAPP_COUNTRY
create unique index IDX_DEALERAPP_COUNTRY_UNIQ_CODE on DEALERAPP_COUNTRY (CODE) ^
create unique index IDX_DEALERAPP_COUNTRY_UNIQ_NAME on DEALERAPP_COUNTRY (NAME) ^
-- end DEALERAPP_COUNTRY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references DEALERAPP_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
-- end SEC_USER
